"""Language choices shared with the top-50 Jev corpus classification."""

LANGUAGES = {
    "en": "English",
    "cmn": "Mandarin Chinese",
    "hi": "Hindi",
    "es": "Spanish",
    "arb": "Modern Standard Arabic",
    "fr": "French",
    "bn": "Bengali",
    "pt": "Portuguese",
    "id": "Indonesian",
    "ur": "Urdu",
    "ru": "Russian",
    "de": "Standard German",
    "ja": "Japanese",
    "pcm": "Nigerian Pidgin",
    "arz": "Egyptian Arabic",
    "mr": "Marathi",
    "vi": "Vietnamese",
    "te": "Telugu",
    "sw": "Swahili",
    "ha": "Hausa",
    "tr": "Turkish",
    "pnb": "Western Punjabi",
    "tl": "Tagalog",
    "ta": "Tamil",
    "yue": "Yue Chinese (Cantonese)",
    "wuu": "Wu Chinese",
    "pes": "Iranian Persian (Farsi)",
    "ko": "Korean",
    "am": "Amharic",
    "th": "Thai",
    "jv": "Javanese",
    "it": "Italian",
    "gu": "Gujarati",
    "kn": "Kannada",
    "apc": "Levantine Arabic",
    "apd": "Sudanese Arabic",
    "bho": "Bhojpuri",
    "pa": "Eastern Punjabi",
    "nan": "Min Nan Chinese",
    "cjy": "Jinyu Chinese",
    "yo": "Yoruba",
    "hak": "Hakka Chinese",
    "my": "Burmese",
    "arq": "Algerian Arabic",
    "pl": "Polish",
    "ln": "Lingala",
    "or": "Odia",
    "ary": "Moroccan Arabic",
    "hsn": "Xiang Chinese",
    "ml": "Malayalam",
    "und": "Undetermined / outside the top 50",
}
